### ISSUE TITLE
Add support for SSE4.2

### ISSUE THREAD

**Issue by CodeMyst** [AuburnSounds/intel-intrinsics#4]
- [x] `_mm_cmpestra`
- [x] `_mm_cmpestrc`
- [x] `_mm_cmpestri`
- [x] `_mm_cmpestrm`
- [x] `_mm_cmpestro`
- [x] `_mm_cmpestrs`
- [x] `_mm_cmpestrz`
- [x] `_mm_cmpgt_epi64`
- [x] `_mm_cmpistra`
- [x] `_mm_cmpistrc`
- [x] `_mm_cmpistri`
- [x] `_mm_cmpistrm`
- [x] `_mm_cmpistro`
- [x] `_mm_cmpistrs`
- [x] `_mm_cmpistrz`
- [x] `_mm_crc32_u16`
- [x] `_mm_crc32_u32`
- [x] `_mm_crc32_u64`
- [x] `_mm_crc32_u8`
- [x] Support signed and unsigned test with `_SIDD_CMP_RANGES`
- [x] Implement the string comparisons with other SIMD
- [x] fix `_SIDD_CMP_EQUAL_ORDERED`
- [x] PERF create a function that return a mask for non-zero chars
- [x] PERF Speed up cmpStr, for example not all comparisons need to be done
- [x] PERF Speed up findLengthByte
- [x] PERF Speed up findLengthShort
- [x] to create a bit mask in case of byte chars we probably want to use `_mm_movemask_epi8`

**Comment by charlesgregory** [comment]
Has there been any work done in this area? If not I can contribute. I have done some work implementing pmmintrin.d (SSE3) for LDC. Mostly done with the LDC implementation, just need to get the DMD implementation working. I would eventually like to tackle AVX and AVX2 as well.

**Comment by p0nce** [comment]
Hello @charlesgregory ,

No I haven't done anything wrt SSE3! You're more than welcome if you want to help with that.

You can absolutely commit LDC-only and leave the DMD ones with an `assert(false)` if you want. Usually the LDC implementation helps debugging it, which is why tests are so helpful. Adding partial implementation for new intrinsics does not break existing code, so it's OK (it won't be OK once the new header is accessible in a tag).

One rule that is not written in that in the D file, intrinsics are in the same physical order in the file than in the Intel guide: https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=SSE3

Will SSE3 get generated by default by LDC?

You can absolutely submit partial work.
(however I suggest we proceed "in order", _finish_ one instruction set completely before going the newer one.)

**Comment by p0nce** [comment]
Lack of SSSE3 annoying to implement more advanced stuff.

**Comment by JohanEngelen** [comment]
> One rule that is not written in that in the D file, intrinsics are in the same physical order in the file than in the Intel guide: https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=SSE3

@p0nce   Perhaps we can spend some time doing the boilerplate/simple work of adding the functions signatures in order, but simply commented out?  It's simple work, and then it makes it a little easier for people to work on whatever intrinsic they fancy?
Same as with already adding the `LDC_with_SSE4` etc.

**Comment by p0nce** [comment]
I'd merge that.

When I work on intel-intrinsics though I tend to prefer to go one-by-one on the intrinsics in order.
In the past I did them not completely, and it was error-prone to go over them to check this or that property.

**Comment by p0nce** [comment]
Status update, 41/61 intrinsics implemented (D_SIMD and ARM32 not done for those and left to an hypothetical future).

**Comment by p0nce** [comment]
SSE4.1 available in `intel-intrinsics` >= v1.5.0 (enabled with `-mattr=+sse4.1` for LDC)

**Comment by p0nce** [comment]
Starting SSE4.2 support

**Comment by p0nce** [comment]
SSE4.2 support in v1.7
