### ISSUE TITLE
Latest release fails on Buildkite

### ISSUE THREAD

**Issue by Geod24** [AuburnSounds/intel-intrinsics#99]
```
core.exception.AssertError@source/inteli/shaintrin.d(255): unittest failure
--
  | ----------------
  | ??:? _d_unittestp [0x4bd4b1]
  | ??:? nothrow @nogc void inteli.shaintrin.__unittest_L249_C1() [0x490a21]
  | ??:? void inteli.shaintrin.__modtest() [0x490a62]
  | ??:? int core.runtime.runModuleUnitTests().__foreachbody6(object.ModuleInfo*) [0x4d092e]
  | ??:? int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)).__lambda2(immutable(object.ModuleInfo*)) [0x4aa40f]
  | ??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))).__foreachbody2(ref rt.sections_elf_shared.DSO) [0x4c9693]
  | ??:? int rt.sections_elf_shared.DSO.opApply(scope int delegate(ref rt.sections_elf_shared.DSO)) [0x4c9ae1]
  | ??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))) [0x4c9621]
  | ??:? int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)) [0x4aa3e1]
  | ??:? runModuleUnitTests [0x4d0766]
  | ??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x4c5344]
  | ??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x4c52d1]
  | ??:? _d_run_main2 [0x4c523a]
  | ??:? _d_run_main [0x4c5023]
  | ??:? main [0x466d59]
  | ??:? __libc_start_main [0x7f05df70b82f]
  | ??:? _start [0x466c48]
  | 1/14 modules FAILED unittests
  | Error Program exited with code 1
```

https://buildkite.com/dlang/dub/builds/2483#0182db98-fe29-4e08-bbf2-686496f8c9e6

**Comment by p0nce** [comment]
> C:\Users\guill\Desktop\intel-intrinsics>dub test -b unittest-release --compiler dmd
Generating test runner configuration 'intel-intrinsics-test-library' for 'library' (library).
Performing "unittest-release" build using dmd for x86_64.
intel-intrinsics 1.10.3: target for configuration "intel-intrinsics-test-library" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running intel-intrinsics-test-library.exe
14 modules passed unittests

> C:\Users\guill\Desktop\intel-intrinsics>dmd --version
DMD32 D Compiler v2.100.0-dirty
Copyright (C) 1999-2022 by The D Language Foundation, All Rights Reserved written by Walter Bright

With 99% certainty this is a DMD bug that should be in the D Bugzilla instead of here. There is nothing to fix in intel-intrinsics, I just make use of the DMD features now.

**Comment by Geod24** [comment]
Well your own CI doesn't pass: https://github.com/AuburnSounds/intel-intrinsics/runs/8036990110?check_suite_focus=true
The question is not about where the bug is, but which CI is failing. Because intel-intrinsics is on Buildkite, and that issue isn't newly introduced AFAICS, we'll have to either disable it on Buildkite, or disable the test here until the bug in DMD is fixed.

**Comment by p0nce** [comment]
I udnerstand that I try to transition when DMD regressions are at a low point, but can't avoid them all.

My CI uses `dmd-latest` so it will break whenever DMD introduces backend regressions because of insufficient testing, and intel-intrinsics is that test-suite.
If you disable intel-intrinsisc from BuildKite then a lot of the DMD backend is simply untested.

**Comment by p0nce** [comment]
Meanwhile it's true this can be workarounded in intel-intrinsics, and I will do so immediately, but please enable back intel-intrinsics in BuildKite when it's done!

**Comment by Geod24** [comment]
We're aware `intel-intrinsics` is probably the best project w.r.t. DMD backend testing, it's simply that we can't block all D development on its CI. Feel free to submit a revert to `dlang/ci` or to ping me when we can re-enable it.

**Comment by p0nce** [comment]
Hello, you can re-enable it now. :) 

`intel-intrinsics` latest should build for you.

The DMD regression is now filed under: https://issues.dlang.org/show_bug.cgi?id=23307

There were other problems, for example using 256-bit __vector in DMD triggered other Linux problems, it seems not all __vector operators exist, so I backed that out (but not the SSE registers) and will wait a few years about it I guess. So there is progress after all. :)
